# Application name
spring.application.name=demo-app

# H2 Database (local profile default)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Custom properties (used with @Value)
app.name=My Spring App
app.version=1.0

# ? NEW (used with @ConfigurationProperties)
app.config.name=MyApp
app.config.version=2.0
app.config.author=Sreeja

# Active profile
spring.profiles.active=local

app.topics=java-spring-boot

app.time.date=2026-05-01
app.time.time=12:30:00
app.time.datetime=2026-05-01T12:30:00
