# =========================================
# APPLICATION
# =========================================
spring.application.name=demo-app

# =========================================
# H2 DATABASE CONFIGURATION
# =========================================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =========================================
# H2 CONSOLE
# =========================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================================
# JPA / HIBERNATE
# =========================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically create/update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# Format SQL nicely
spring.jpa.properties.hibernate.format_sql=true

# =========================================
# HIBERNATE QUERY LOGGING
# =========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# =========================================
# CUSTOM PROPERTIES
# =========================================
app.name=My Spring App
app.version=1.0

# =========================================
# CONFIGURATION PROPERTIES
# =========================================
app.config.name=MyApp
app.config.version=2.0
app.config.author=Sreeja

# =========================================
# ACTIVE PROFILE
# =========================================
spring.profiles.active=local

# =========================================
# SpEL
# =========================================
app.topics=java-spring-boot

# =========================================
# DATE / TIME
# =========================================
app.time.date=2026-05-01
app.time.time=12:30:00
app.time.datetime=2026-05-01T12:30:00

# =========================================
# DEBUG MODE
# =========================================
debug=true